<template>
  <div class="race">
    
    <!-- https://art.hearthstonejson.com/v1/render/latest/${type == 'kr' ? 'koKR' : 'enUS'}/256x/${path}.png -->
    
    <!-- <img
    v-for="card in tests"
    :key="card"
    :src="`https://art.hearthstonejson.com/v1/render/latest/koKR/256x/${card}.png`"
    :alt="card" /> -->
   
    <img
    v-for="card in tests"
    :key="card"
    :src="`https://art.hearthstonejson.com/v1/256x/${card}.jpg`"
    :alt="card" />

    <!-- orig, 256x, 512x -->

  </div>
</template>

<script>
import common from '@/mixins/common';

export default {
  name: 'race',
  mixins: [common],
  data: () => {
    return {
      cards: [
        'AT_121',
        'BGS_001',
        'BGS_002',
        'BGS_004',
        'BGS_006',
        'BGS_008',
        'BGS_009',
        'BGS_010',
        'BGS_012',
        'BGS_014',
        'BGS_017',
        'BGS_018',
        'BGS_019',
        'BGS_020',
        'BGS_021',
        'BGS_022',
        'BGS_023',
        'BGS_024',
        'BGS_025',
        'BGS_027',
        'BGS_028',
        'BGS_029',
        'BGS_030',
        'BGS_031',
        'BGS_032',
        'BGS_033',
        'BGS_034',
        'BGS_035',
        'BGS_036',
        'BGS_037',
        'BGS_038',
        'BGS_039',
        'BGS_040',
        'BGS_041',
        'BGS_043',
        'BGS_044',
        'BGS_045',
        'BGS_059',
        'BGS_067',
        'BGS_068',
        'BGS_071',
        'BOT_218',
        'BOT_312',
        'BOT_445',
        'BOT_537',
        'BOT_606',
        'BOT_911',
        'CFM_315',
        'CFM_316',
        'CFM_610',
        'CFM_816',
        'DS1_070',
        'EX1_062',
        'EX1_093',
        'EX1_103',
        'EX1_162',
        'EX1_185',
        'EX1_506',
        'EX1_507',
        'EX1_509',
        'EX1_531',
        'EX1_534',
        'EX1_556',
        'EX1_577',
        'GVG_021',
        'GVG_027',
        'GVG_048',
        'GVG_055',
        'GVG_062',
        'GVG_100',
        'GVG_113',
        'KAR_095',
        'KAR_702',
        'LOOT_013',
        'LOOT_078',
        'LOOT_368',
        'OG_221',
        'DAL_077',
        'ICC_029',
        'UNG_073',
        'OG_256',
        'ICC_858',
        'TB_BaconShop_HP_033t',
        'BRM_006',
        'YOD_026',
        'ICC_038',
        'FP1_024',
        'KAR_005',
        'OG_216',
        'LOE_077',
        'ICC_807',
        'FP1_031',
        'TRL_232',
        'GVG_106',
        'TB_BaconShop_HP_047t',
        'DAL_575',
        'FP1_010',
        'TB_BaconUps_002',
        'TB_BaconUps_002t',
        'TB_BaconUps_003',
        'TB_BaconUps_003t',
        'TB_BaconUps_004',
        'TB_BaconUps_004t',
        'TB_BaconUps_006',
        'TB_BaconUps_006t',
        'TB_BaconUps_008',
        'TB_BaconUps_009',
        'TB_BaconUps_011',
        'TB_BaconUps_014',
        'TB_BaconUps_019',
        'TB_BaconUps_025',
        'TB_BaconUps_026',
        'TB_BaconUps_026t',
        'TB_BaconUps_027',
        'TB_BaconUps_027t',
        'TB_BaconUps_028',
        'TB_BaconUps_030',
        'TB_BaconUps_030t',
        'TB_BaconUps_031',
        'TB_BaconUps_032',
        'TB_BaconUps_032t',
        'TB_BaconUps_033',
        'TB_BaconUps_034',
        'TB_BaconUps_035',
        'TB_BaconUps_036',
        'TB_BaconUps_037',
        'TB_BaconUps_038',
        'TB_BaconUps_039',
        'TB_BaconUps_039t',
        'TB_BaconUps_040',
        'TB_BaconUps_040t',
        'TB_BaconUps_041',
        'TB_BaconUps_041t',
        'TB_BaconUps_042',
        'TB_BaconUps_043',
        'TB_BaconUps_044',
        'TB_BaconUps_045',
        'TB_BaconUps_046',
        'TB_BaconUps_047',
        'TB_BaconUps_049',
        'TB_BaconUps_049t',
        'TB_BaconUps_050',
        'TB_BaconUps_051',
        'TB_BaconUps_051t',
        'TB_BaconUps_052',
        'TB_BaconUps_052t',
        'TB_BaconUps_053',
        'TB_BaconUps_055',
        'TB_BaconUps_057',
        'TB_BaconUps_058',
        'TB_BaconUps_059',
        'TB_BaconUps_059t',
        'TB_BaconUps_060',
        'TB_BaconUps_061',
        'TB_BaconUps_062',
        'TB_BaconUps_063',
        'TB_BaconUps_064',
        'TB_BaconUps_066',
        'TB_BaconUps_068',
        'TB_BaconUps_069',
        'TB_BaconUps_070',
        'TB_BaconUps_072',
        'TB_BaconUps_073',
        'TB_BaconUps_074',
        'TB_BaconUps_075',
        'TB_BaconUps_077',
        'TB_BaconUps_079',
        'TB_BaconUps_080',
        'TB_BaconUps_082',
        'TB_BaconUps_083',
        'TB_BaconUps_084',
        'TB_BaconUps_085',
        'TB_BaconUps_086',
        'TB_BaconUps_087',
        'TB_BaconUps_088',
        'TB_BaconUps_089',
        'TB_BaconUps_090',
        'TB_BaconUps_091',
        'TB_BaconUps_093',
        'TB_BaconUps_093t',
        'TB_BaconUps_094',
        'TB_BaconUps_095',
        'TB_BaconUps_099',
        'TB_BaconUps_100',
        'TB_BaconUps_101',
        'TB_BaconUps_102',
        'TB_BaconUps_103',
        'TB_BaconUps_104',
        'TB_BaconUps_105',
        'TB_BaconUps_106',
        'TB_BaconUps_107',
        'TB_BaconUps_108',
        'TB_BaconUps_109',
        'TB_BaconUps_110',
        'TB_BaconUps_112',
        'TB_BaconUps_113',
        'TB_BaconUps_115',
        'TB_BaconUps_116',
        'TB_BaconUps_117',
        'TB_BaconUps_118',
        'TB_BaconUps_119',
        'TB_BaconUps_120',
        'TB_BaconUps_123'
      ],
      heros: [
        'TB_BaconShop_HERO_KelThuzad',
        'TB_BaconShop_HERO_08',
        'TB_BaconShop_HERO_16',
        'TB_BaconShop_HERO_56',
        'TB_BaconShop_HERO_45',
        'TB_BaconShop_HERO_PH',
        'TB_BaconShop_HERO_31',
        'TB_BaconShop_HERO_36',
        'TB_BaconShop_HERO_52',
        'TB_BaconShop_HERO_43',
        'TB_BaconShop_HERO_01',
        'TB_BaconShop_HERO_42',
        'TB_BaconShop_HERO_55',
        'TB_BaconShop_HERO_02',
        'TB_BaconShop_HERO_15',
        'TB_BaconShop_HERO_19',
        'TB_BaconShop_HERO_28',
        'TB_BaconShop_HERO_38',
        'TB_BaconShop_HERO_25',
        'TB_BaconShop_HERO_37',
        'TB_BaconShop_HERO_58',
        'TB_BaconShop_HERO_49',
        'TB_BaconShop_HERO_17',
        'TB_BaconShop_HERO_30',
        'TB_BaconShop_HERO_57',
        'TB_BaconShop_HERO_18',
        'TB_BaconShop_HERO_34',
        'TB_BaconShop_HERO_20',
        'TB_BaconShop_HERO_39',
        'TB_BaconShop_HERO_14',
        'TB_BaconShop_HERO_11',
        'TB_BaconShop_HERO_41',
        'TB_BaconShop_HERO_23',
        'TB_BaconShop_HERO_27',
        'TB_BaconShop_HERO_40',
        'TB_BaconShop_HERO_44',
        'TB_BaconShop_HERO_33',
        'TB_BaconShop_HERO_21',
        'TB_BaconShop_HERO_22',
        'TB_BaconShop_HERO_12',
        'TB_BaconShop_HERO_47',
        'TB_BaconShop_HERO_10',
        'TB_BaconShop_HERO_35',
        'TB_BaconShop_HERO_53'
      ],
      buttons: [
        'DALA_BOSS_99h',
        'TB_BaconShop_Triples_01',
        'TB_BaconShopTechUp02_Button',
        'TB_BaconShopTechUp03_Button',
        'TB_BaconShopTechUp04_Button',
        'TB_BaconShopTechUp05_Button',
        'TB_BaconShopTechUp06_Button',
        'TB_BaconShopLockAll_Button'
      ],
      powers: [
        'TB_BaconUps_124',
        'TB_BaconShop_HP_057',
        'TB_BaconShop_HP_035',
        'TB_BaconShop_HP_061',
        'TB_BaconShop_HP_052',
        'TB_BaconShop_HP_050',
        'TB_BaconShop_HP_048',
        'TB_BaconShop_HP_036',
        'TB_BaconShop_HP_010',
        'TB_BaconShop_HP_040',
        'TB_BaconShop_HP_022',
        'TB_BaconShop_HP_063',
        'TB_BaconShop_HP_019',
        'TB_BaconShop_HP_062',
        'TB_BaconShop_HP_027',
        'TB_BaconShop_HP_011',
        'TB_BaconShop_HP_056',
        'TB_BaconShop_HP_046',
        'TB_BaconShop_HP_049',
        'TB_BaconShop_HP_042',
        'TB_BaconShop_HP_051',
        'TB_BaconShop_HP_053',
        'TB_BaconShop_HP_041a',
        'TB_BaconShop_HP_041d',
        'TB_BaconShop_HP_041f',
        'TB_BaconShop_HP_041b',
        'TB_BaconShop_HP_041c',
        'TB_BaconShop_HP_047',
        'TB_BaconShop_HP_054',
        'TB_BaconShop_HP_033',
        'TB_BaconShop_HP_017',
        'TB_BaconShop_HP_043',
        'TB_BaconShop_HP_020',
        'TB_BaconShop_HP_044',
        'TB_BaconShop_HP_039',
        'TB_BaconShop_HP_064',
        'TB_BaconShop_HP_018',
        'TB_BaconShop_HP_024',
        'TB_BaconShop_HP_001',
        'TB_BaconShop_HP_009',
        'TB_BaconShop_HP_008',
        'TB_BaconShop_HP_014',
        'TB_BaconShop_HP_028',
        'TB_BaconShop_HP_015',
        'TB_BaconShop_HP_037a',
        'TB_BaconShop_HP_069'
      ],
      tests: [
        // 'TB_BaconShop_HERO_75',
        // 'TB_BaconShop_HERO_76',
        // 'TB_BaconShop_HERO_78',
        // 'TB_BaconShop_HP_085',
        // 'TB_BaconShop_HP_086',
        // 'TB_BaconShop_HP_087',
        // 'TB_BaconShop_HP_088'
      ]
    }
  },
  mounted() {
  },
  methods: {
  }
}
</script>

<style scoped lang="scss">
</style>
